### PR TITLE
Update fork to 5.0.2

### PR DESCRIPTION
**Pull request by SergioEstevao**
Update fork to version 5.0.2 of the original repo.

### CODE REVIEW

**Comment by hypest** [comment]
👋 Sérgio, let's open a gutenberg-mobile PR as well, to test this and only merge when everything looks ok. Thanks!

**Comment by hypest** [comment]
Is seems that many commits are already on the `fork-for-gutenberg-mobile` branch. Any info on why this PR/branch adds them again?

**Comment by SergioEstevao** [comment]
I did a rebase of 5.0.2 tag to this branch...could that be the reason?

**Comment by hypest** [comment]
> I did a rebase of 5.0.2 tag to this branch...could that be the reason?

Hmm, most probably, yeah. Thing is, even though the diff itself is fairly trivial and easy to review, it's not clear what commits we bring in from master (which tracks upstream) and messes up the history, possibly making debugging issues a bit harder. Can we do a branch merge instead of a rebase instead? Were there non-trivial conflicts perhaps, if you tried it?

**Comment by SergioEstevao** [comment]
Closed in favour of this PR: https://github.com/wordpress-mobile/react-native-video/pull/8

@hypest can you give a look to the PR above?

**Pull request closed without merging**
