### PR TITLE
Update to 5.2.0-wp-2

### PR DESCRIPTION
**Pull request by mchowning**
I didn't realize that we had already created a `5.2.0-wp-1` tag when I updated to that version ([commit](https://github.com/wordpress-mobile/react-native-video/pull/15/commits/3d808258520f8ecdebcc3c91702c717a137da934), [PR](https://github.com/wordpress-mobile/react-native-video/pull/15)). Bumping the version and rebuilding the tarball just so I can tag the merge commit from this PR with `5.2.0-wp-2` (that seemed better than moving the `5.2.0-wp-1` tag even though I don't think we're using it).

### CODE REVIEW

**Comment by hypest** [comment]
Shall we remove the `5.2.0-wp-1` tarball? I think that we access the tarball via the tag/hash anyway and only 1 tarball would need to be avail in the file tree?

**Comment by mchowning** [comment]
> Shall we remove the 5.2.0-wp-1 tarball? I think that we access the tarball via the tag/hash anyway and only 1 tarball would need to be avail in the file tree?

Thanks for catching that. Leaving it was just a miss on my part. Should be gone now.

**Comment by hypest** [comment]
PR looks good to me Matt, wondering if you have a gutenberg-mobile PR to test it from, just to be sure that it can be consumed correctly?

**Comment by mchowning** [comment]
Sure, the references in the [gb](https://github.com/WordPress/gutenberg/pull/38426) and [gb-mobile](https://github.com/wordpress-mobile/gutenberg-mobile/pull/4361) are now updated. Obviously, I'll update them again once this PR is merged and tagged.

**Review by hypest — APPROVED** [review]
LGTM!

Tried it locally and the video background on a cover block works fine 👍

**Pull request merged**
