### PR TITLE
Update from upstream v5.2.0

### PR DESCRIPTION
**Pull request by hypest**
Draft PR to try out updating from upstream, to bring in updated version of ExoPlayer.

### CODE REVIEW

**Comment by mchowning** [comment]
I created [a separate PR](https://github.com/WordPress/gutenberg/pull/38426) proposing we bump exoplayer to a slightly higher version.

**Review by mchowning — APPROVED** [review]
This is working well in my testing. We just need to remember to create the `5.2.0-wp-1` tag once this is merged and update the reference in https://github.com/WordPress/gutenberg/pull/38426.

I'm not merging this since I did the latest changes, and I wanted to give you a chance to review them @hypest .

**Comment by mchowning** [comment]
Note that in [faecf40](https://github.com/wordpress-mobile/react-native-video/pull/15/commits/faecf4091d896d5efa3dc030e2d233cbf974a368) I removed the Apache dependencies that were accidentally included when resolving a merge conflict. They were previously removed in earlier PRs ([shaka](https://github.com/wordpress-mobile/react-native-video/commit/5c6697afc5244883615acc84f054a1ed2a0c6ed0), [keymirror](https://github.com/wordpress-mobile/react-native-video/commit/148b6177469f629538f4dc5539c741d0bb633020)).

**Comment by hypest** [comment]
Thanks for the extra context @mchowning ! Tried it locally with the gutenberg-mobile demo app and a video-background on a Cover block and works fine. Looks good to me 👍

**Pull request merged**
